export const environment = {
  production: false,
  API_URL: 'https://bunnycarhire.co.za/api/',
  // BASE_URL: 'https://bunnycarhire.co.za/',
  // API_URL: 'https://bunnycarhire.co.za//api',
  // BASE_URL: 'https://bunnycarhire.co.za/',
  // API_URL: 'http://localhost:8200/api-tybo-accounting',
  BASE_URL: 'http://localhost:4200',
  BASE_URL_ADMIN: 'http://localhost:4200',
  ACCOUNT_TEST_EMAIL: 'info@bunnycarhire.co.za',
  ACCOUNT_TEST_PASSWORD: 'info@bunnycarhire.co.za',
  TEST_EMAIL_ACCOUNT: 'admin@tybo-services.co.za',
  DF_LOGO: `https://bunnycarhire.co.za/api//api/upload/uploads/1625394631iio.jpg`,
  DF_USER_LOGO: `https://bunnycarhire.co.za/api//api/upload/uploads/1625394631iio.jpg`,
};
